plugins {
    id 'java-library'
}

dependencyManagement {
    imports {
        mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
    }
}

dependencies {
    implementation project(':lore-core:lore-core-base')  // 依赖 domain 模块

    api 'org.springframework.boot:spring-boot-starter-validation'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add("-parameters")
}
