### test environment ###

######### 应用自定义配置 #########
my-app:
  file-location: ./file/
  hostname: localhost
  jwt-expire-time: 86400000

############ server ############
server:
  forward-headers-strategy: native
  port: ${port:8080}
  http2:
    enabled: true
  compression:
    enabled: true
  tomcat:
    basedir: ./tomcat/
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto

########## database init ##########
spring.sql:
  init:
    # 这个值会被 DatabaseInitializer.java 修改
    mode: always
    username: root
    password: root
    encoding: UTF-8
    schema-locations:
      - classpath:db/schema-mysql.sql
      # 指定文件创建的位置, DatabaseInitializer.java会创建文件及内容
      - file:./change-passwd.sql
    data-locations: classpath:db/data-mysql.sql

########## datasource ##########
spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  # characterEncoding=UTF-8, 对于8.0.12及更早版本将映射到MySQL字符集名称utf8, 对于8.0.13及更高版本将映射到MySQL字符集名称utf8mb4
  url: jdbc:mysql://db:3306/${spring.datasource.hikari.schema}
  username: root
  password: rUbdTVegr1nueOx4/WIgxw==
  hikari:
    schema: lore_blog
    data-source-properties:
      # 自定义配置
      characterEncoding: UTF-8
      zeroDateTimeBehavior: convertToNull
      serverTimezone: GMT+8
      # 优化配置
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false

######### mybatis-plus #########
mybatis-plus:
  typeAliasesPackage: com.developerchen.core.domain.entity, com.developerchen.*.module.*.domain.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_ID
      table-underline: true
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_null

########## thymeleaf ##########
spring.thymeleaf:
  excluded-view-names: admin/index
