spring:
  profiles:
    active: dev
  application:
    name: blog

########## security ##########
  security:
    user:
      name: user
      password: user

########## actuator ##########
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
