### development environment ###

######### 应用自定义配置 #########
my-app:
  file-location: E:\lore-blog\file\
  scheme: http
  hostname: 127.0.0.1
  jwt-expire-time: 864000000

############ server ############
server:
  tomcat:
    uri-encoding: UTF-8
    basedir: E:\lore-blog\tomcat\
  port: ${port:8080}

########## datasource ##########
# 配置属性列表详细说明 https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  # characterEncoding=UTF-8, 对于8.0.12及更早版本将映射到MySQL字符集名称utf8, 对于8.0.13及更高版本将映射到MySQL字符集名称utf8mb4
  url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.hikari.schema}
  username: root
  password: root
  hikari:
    schema: lore_blog
    data-source-properties:
      # 自定义配置
      characterEncoding: UTF-8
      zeroDateTimeBehavior: convertToNull
      serverTimezone: GMT+8
      # 优化配置
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false

######### mybatis-plus #########
mybatis-plus:
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.developerchen.core.domain.entity, com.developerchen.*.module.*.domain.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
  global-config:
    banner: false
    db-config:
      # 主键类型
      id-type: ASSIGN_ID
      # 表名是否使用下划线命名
      table-underline: true
      # 字段验证策略 ignored:"忽略判断",not_null:"非 NULL 判断"),not_empty:"非空判断"
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_null

########## thymeleaf ##########
spring.thymeleaf:
  # development环境下关闭缓存
  cache: false
  excluded-view-names: admin/index

########## JMX ##########
spring:
  jmx:
    enabled: true
    default-domain: ${my-app.hostname}
  application:
    admin:
      enabled: false
