plugins {
    id 'java-library'
}

dependencyManagement {
    imports {
        mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
    }
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter-web'

    api 'com.baomidou:mybatis-plus-core:3.5.12'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.add("-parameters")
}
