plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':core')  // 依赖 core 模块

    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-authorization-server'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
    implementation 'com.baomidou:mybatis-plus-spring-boot3-starter:3.5.10.1'
    implementation 'com.baomidou:mybatis-plus-jsqlparser:3.5.10.1'
    implementation('com.vladsch.flexmark:flexmark-all:0.64.8') {
        exclude group: "com.vladsch.flexmark", module: "flexmark-youtrack-converter"
        exclude group: "com.vladsch.flexmark", module: "flexmark-pdf-converter"
        exclude group: "com.vladsch.flexmark", module: "flexmark-jira-converter"
        exclude group: "com.vladsch.flexmark", module: "flexmark-ext-youtube-embedded"
    }
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'

    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
}
